### ISSUE TITLE
在use_attention=False会报错

### ISSUE THREAD

**Issue by lzh66** [TolicWang/RNN#2]
在use_attention=False会报错

0-10-09 19:18:06.502392: W tensorflow/core/framework/op_kernel.cc:1502] OP_REQUIRES failed at save_restore_v2_ops.cc:184 : Not found: Key decoder_1/multi_rnn_cell/cell_0/lstm_cell/bias not found in checkpoint
Traceback (most recent call last):
  File "D:\anaconda\envs\torchgpu\lib\site-packages\tensorflow\python\client\session.py", line 1356, in _do_call
    return fn(*args)
  File "D:\anaconda\envs\torchgpu\lib\site-packages\tensorflow\python\client\session.py", line 1341, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "D:\anaconda\envs\torchgpu\lib\site-packages\tensorflow\python\client\session.py", line 1429, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.NotFoundError: Key decoder_1/multi_rnn_cell/cell_0/lstm_cell/bias not found in checkpoint
	 [[{{node save/RestoreV2}}]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\anaconda\envs\torchgpu\lib\site-packages\tensorflow\python\training\saver.py", line 1286, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "D:\anaconda\envs\torchgpu\lib\site-packages\tensorflow\python\client\session.py", line 950, in run
    run_metadata_ptr)
  File "D:\anaconda\envs\torchgpu\lib\site-packages\tensorflow\python\client\session.py", line 1173, in _run
    feed_dict_tensor, options, run_metadata)
  File "D:\anaconda\envs\torchgpu\lib\site-packages\tensorflow\python\client\session.py", line 1350, in _do_run
    run_metadata)
  File "D:\anaconda\envs\torchgpu\lib\site-packages\tensorflow\python\client\session.py", line 1370, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.NotFoundError: Key decoder_1/multi_rnn_cell/cell_0/lstm_cell/bias not found in checkpoint
	 [[node save/RestoreV2 (defined at \untitled\study\Example_4\model.py:201) ]]

Original stack trace for 'save/RestoreV2':
  File "/untitled/study/Example_4/train.py", line 27, in <module>
    model.train(source_input, target_input, target_output, src_vocab_table, tgt_vocab_table, data.gen_batch)
  File "\untitled\study\Example_4\model.py", line 201, in train
    saver = tf.train.Saver(params, max_to_keep=10)
  File "\anaconda\envs\torchgpu\lib\site-packages\tensorflow\python\training\saver.py", line 825, in __init__
    self.build()
  File "\anaconda\envs\torchgpu\lib\site-packages\tensorflow\python\training\saver.py", line 837, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "\anaconda\envs\torchgpu\lib\site-packages\tensorflow\python\training\saver.py", line 875, in _build
    build_restore=build_restore)
  File "\anaconda\envs\torchgpu\lib\site-packages\tensorflow\python\training\saver.py", line 508, in _build_internal
    restore_sequentially, reshape)
  File "\anaconda\envs\torchgpu\lib\site-packages\tensorflow\python\training\saver.py", line 328, in _AddRestoreOps
    restore_sequentially)
  File "\anaconda\envs\torchgpu\lib\site-packages\tensorflow\python\training\saver.py", line 575, in bulk_restore
    return io_ops.restore_v2(filename_tensor, names, slices, dtypes)
  File "\anaconda\envs\torchgpu\lib\site-packages\tensorflow\python\ops\gen_io_ops.py", line 1779, in restore_v2
    name=name)
  File "\anaconda\envs\torchgpu\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "\anaconda\envs\torchgpu\lib\site-packages\tensorflow\python\util\deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "\anaconda\envs\torchgpu\lib\site-packages\tensorflow\python\framework\ops.py", line 3616, in create_op
    op_def=op_def)
  File "\anaconda\envs\torchgpu\lib\site-packages\tensorflow\python\framework\ops.py", line 2005, in __init__
    self._traceback = tf_stack.extract_stack()

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\anaconda\envs\torchgpu\lib\site-packages\tensorflow\python\training\saver.py", line 1296, in restore
    names_to_keys = object_graph_key_mapping(save_path)
  File "D:\anaconda\envs\torchgpu\lib\site-packages\tensorflow\python\training\saver.py", line 1614, in object_graph_key_mapping
    object_graph_string = reader.get_tensor(trackable.OBJECT_GRAPH_PROTO_KEY)
  File "D:\anaconda\envs\torchgpu\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 678, in get_tensor
    return CheckpointReader_GetTensor(self, compat.as_bytes(tensor_str))
tensorflow.python.framework.errors_impl.NotFoundError: Key _CHECKPOINTABLE_OBJECT_GRAPH not found in checkpoint

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:/untitled/study/Example_4/train.py", line 27, in <module>
    model.train(source_input, target_input, target_output, src_vocab_table, tgt_vocab_table, data.gen_batch)
  File "D:\untitled\study\Example_4\model.py", line 209, in train
    saver.restore(sess, check_point)
  File "D:\anaconda\envs\torchgpu\lib\site-packages\tensorflow\python\training\saver.py", line 1302, in restore
    err, "a Variable name or other graph key that is missing")
tensorflow.python.framework.errors_impl.NotFoundError: Restoring from checkpoint failed. This is most likely due to a Variable name or other graph key that is missing from the checkpoint. Please ensure that you have not altered the graph expected based on the checkpoint. Original error:

Key decoder_1/multi_rnn_cell/cell_0/lstm_cell/bias not found in checkpoint
	 [[node save/RestoreV2 (defined at \untitled\study\Example_4\model.py:201) ]]

Original stack trace for 'save/RestoreV2':
  File "/untitled/study/Example_4/train.py", line 27, in <module>
    model.train(source_input, target_input, target_output, src_vocab_table, tgt_vocab_table, data.gen_batch)
  File "\untitled\study\Example_4\model.py", line 201, in train
    saver = tf.train.Saver(params, max_to_keep=10)
  File "\anaconda\envs\torchgpu\lib\site-packages\tensorflow\python\training\saver.py", line 825, in __init__
    self.build()
  File "\anaconda\envs\torchgpu\lib\site-packages\tensorflow\python\training\saver.py", line 837, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "\anaconda\envs\torchgpu\lib\site-packages\tensorflow\python\training\saver.py", line 875, in _build
    build_restore=build_restore)
  File "\anaconda\envs\torchgpu\lib\site-packages\tensorflow\python\training\saver.py", line 508, in _build_internal
    restore_sequentially, reshape)
  File "\anaconda\envs\torchgpu\lib\site-packages\tensorflow\python\training\saver.py", line 328, in _AddRestoreOps
    restore_sequentially)
  File "\anaconda\envs\torchgpu\lib\site-packages\tensorflow\python\training\saver.py", line 575, in bulk_restore
    return io_ops.restore_v2(filename_tensor, names, slices, dtypes)
  File "\anaconda\envs\torchgpu\lib\site-packages\tensorflow\python\ops\gen_io_ops.py", line 1779, in restore_v2
    name=name)
  File "\anaconda\envs\torchgpu\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "\anaconda\envs\torchgpu\lib\site-packages\tensorflow\python\util\deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "\anaconda\envs\torchgpu\lib\site-packages\tensorflow\python\framework\ops.py", line 3616, in create_op
    op_def=op_def)
  File "\anaconda\envs\torchgpu\lib\site-packages\tensorflow\python\framework\ops.py", line 2005, in __init__
    self._traceback = tf_stack.extract_stack()

**Comment by TolicWang** [comment]
你这是不是先用了use_attention=True跑了模型，然后马上又改为use_attention=False来跑？ 如果是这样的话可能是由于没有删除之前的模型导致的。你把保存过的模型删掉再试试
